
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using ResoniteLink;

public static class FieldConverter
{
    public static Field ToResoniteLinkField<T>(this T value)
    {
        switch(value)
        {
            // Unity Primitives (and our extensions)
                            case UnityEngine.Vector2 Vector2_value: return Vector2_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3 Vector3_value: return Vector3_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4 Vector4_value: return Vector4_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Quaternion Quaternion_value: return Quaternion_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Int Vector2Int_value: return Vector2Int_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Int Vector3Int_value: return Vector3Int_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Matrix4x4 Matrix4x4_value: return Matrix4x4_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Color Color_value: return Color_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Color32 Color32_value: return Color32_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Rect Rect_value: return Rect_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.RectInt RectInt_value: return RectInt_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.QuaternionDouble QuaternionDouble_value: return QuaternionDouble_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.ColorX ColorX_value: return ColorX_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Bool Vector2Bool_value: return Vector2Bool_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Bool Vector3Bool_value: return Vector3Bool_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Bool Vector4Bool_value: return Vector4Bool_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Byte Vector2Byte_value: return Vector2Byte_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Byte Vector3Byte_value: return Vector3Byte_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Byte Vector4Byte_value: return Vector4Byte_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Ushort Vector2Ushort_value: return Vector2Ushort_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Ushort Vector3Ushort_value: return Vector3Ushort_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Ushort Vector4Ushort_value: return Vector4Ushort_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Uint Vector2Uint_value: return Vector2Uint_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Uint Vector3Uint_value: return Vector3Uint_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Uint Vector4Uint_value: return Vector4Uint_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Ulong Vector2Ulong_value: return Vector2Ulong_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Ulong Vector3Ulong_value: return Vector3Ulong_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Ulong Vector4Ulong_value: return Vector4Ulong_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Sbyte Vector2Sbyte_value: return Vector2Sbyte_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Sbyte Vector3Sbyte_value: return Vector3Sbyte_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Sbyte Vector4Sbyte_value: return Vector4Sbyte_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Short Vector2Short_value: return Vector2Short_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Short Vector3Short_value: return Vector3Short_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Short Vector4Short_value: return Vector4Short_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Long Vector2Long_value: return Vector2Long_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Long Vector3Long_value: return Vector3Long_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Long Vector4Long_value: return Vector4Long_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector2Double Vector2Double_value: return Vector2Double_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector3Double Vector3Double_value: return Vector3Double_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Vector4Double Vector4Double_value: return Vector4Double_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Matrix2x2 Matrix2x2_value: return Matrix2x2_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Matrix3x3 Matrix3x3_value: return Matrix3x3_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Matrix2x2Double Matrix2x2Double_value: return Matrix2x2Double_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Matrix3x3Double Matrix3x3Double_value: return Matrix3x3Double_value.ToResoniteLink().ToResoniteLinkField();
                                case UnityEngine.Matrix4x4Double Matrix4x4Double_value: return Matrix4x4Double_value.ToResoniteLink().ToResoniteLinkField();
                
            // All other primitives
                    case byte byte_value: return new Field_byte() { Value = byte_value };
                        case ushort ushort_value: return new Field_ushort() { Value = ushort_value };
                        case uint uint_value: return new Field_uint() { Value = uint_value };
                        case ulong ulong_value: return new Field_ulong() { Value = ulong_value };
                        case sbyte sbyte_value: return new Field_sbyte() { Value = sbyte_value };
                        case short short_value: return new Field_short() { Value = short_value };
                        case int int_value: return new Field_int() { Value = int_value };
                        case long long_value: return new Field_long() { Value = long_value };
                        case float float_value: return new Field_float() { Value = float_value };
                        case double double_value: return new Field_double() { Value = double_value };
                        case decimal decimal_value: return new Field_decimal() { Value = decimal_value };
                        case bool bool_value: return new Field_bool() { Value = bool_value };
                        case char char_value: return new Field_char() { Value = char_value };
                        case string string_value: return new Field_string() { Value = string_value };
                        case Uri Uri_value: return new Field_Uri() { Value = Uri_value };
                        case DateTime DateTime_value: return new Field_DateTime() { Value = DateTime_value };
                        case TimeSpan TimeSpan_value: return new Field_TimeSpan() { Value = TimeSpan_value };
                        case color color_value: return new Field_color() { Value = color_value };
                        case colorX colorX_value: return new Field_colorX() { Value = colorX_value };
                        case color32 color32_value: return new Field_color32() { Value = color32_value };
                        case Rect Rect_value: return new Field_Rect() { Value = Rect_value };
                        case IntRect IntRect_value: return new Field_IntRect() { Value = IntRect_value };
                        case float2 float2_value: return new Field_float2() { Value = float2_value };
                        case double2 double2_value: return new Field_double2() { Value = double2_value };
                        case byte2 byte2_value: return new Field_byte2() { Value = byte2_value };
                        case ushort2 ushort2_value: return new Field_ushort2() { Value = ushort2_value };
                        case uint2 uint2_value: return new Field_uint2() { Value = uint2_value };
                        case ulong2 ulong2_value: return new Field_ulong2() { Value = ulong2_value };
                        case sbyte2 sbyte2_value: return new Field_sbyte2() { Value = sbyte2_value };
                        case short2 short2_value: return new Field_short2() { Value = short2_value };
                        case int2 int2_value: return new Field_int2() { Value = int2_value };
                        case long2 long2_value: return new Field_long2() { Value = long2_value };
                        case bool2 bool2_value: return new Field_bool2() { Value = bool2_value };
                        case float3 float3_value: return new Field_float3() { Value = float3_value };
                        case double3 double3_value: return new Field_double3() { Value = double3_value };
                        case byte3 byte3_value: return new Field_byte3() { Value = byte3_value };
                        case ushort3 ushort3_value: return new Field_ushort3() { Value = ushort3_value };
                        case uint3 uint3_value: return new Field_uint3() { Value = uint3_value };
                        case ulong3 ulong3_value: return new Field_ulong3() { Value = ulong3_value };
                        case sbyte3 sbyte3_value: return new Field_sbyte3() { Value = sbyte3_value };
                        case short3 short3_value: return new Field_short3() { Value = short3_value };
                        case int3 int3_value: return new Field_int3() { Value = int3_value };
                        case long3 long3_value: return new Field_long3() { Value = long3_value };
                        case bool3 bool3_value: return new Field_bool3() { Value = bool3_value };
                        case float4 float4_value: return new Field_float4() { Value = float4_value };
                        case double4 double4_value: return new Field_double4() { Value = double4_value };
                        case byte4 byte4_value: return new Field_byte4() { Value = byte4_value };
                        case ushort4 ushort4_value: return new Field_ushort4() { Value = ushort4_value };
                        case uint4 uint4_value: return new Field_uint4() { Value = uint4_value };
                        case ulong4 ulong4_value: return new Field_ulong4() { Value = ulong4_value };
                        case sbyte4 sbyte4_value: return new Field_sbyte4() { Value = sbyte4_value };
                        case short4 short4_value: return new Field_short4() { Value = short4_value };
                        case int4 int4_value: return new Field_int4() { Value = int4_value };
                        case long4 long4_value: return new Field_long4() { Value = long4_value };
                        case bool4 bool4_value: return new Field_bool4() { Value = bool4_value };
                        case floatQ floatQ_value: return new Field_floatQ() { Value = floatQ_value };
                        case doubleQ doubleQ_value: return new Field_doubleQ() { Value = doubleQ_value };
                        case float2x2 float2x2_value: return new Field_float2x2() { Value = float2x2_value };
                        case double2x2 double2x2_value: return new Field_double2x2() { Value = double2x2_value };
                        case float3x3 float3x3_value: return new Field_float3x3() { Value = float3x3_value };
                        case double3x3 double3x3_value: return new Field_double3x3() { Value = double3x3_value };
                        case float4x4 float4x4_value: return new Field_float4x4() { Value = float4x4_value };
                        case double4x4 double4x4_value: return new Field_double4x4() { Value = double4x4_value };
                    }

        throw new NotSupportedException($"Unsupported value type: {typeof(T).FullName}");
    }
}