
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using ResoniteLink;
using System.Collections.Generic;
using System.Linq;

public static class FieldArrayConverter
{
    public static Field ToResoniteLinkField<T>(this T value)
    {
        var type = typeof(T);

        if(Nullable.GetUnderlyingType(type)?.IsEnum == true)
        {
            return new Field_Nullable_Enum() 
            {
                Value = value?.ToString()  
            };
        }
        else if(type.IsEnum)
        {
            return new Field_Enum() 
            {
                Value = value.ToString()  
            };
        }

        // Unity Primitives (and our extensions)
                    if(value is UnityEngine.Vector2 value_Vector2)
                return value_Vector2.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2?))
            {
                var convertedValue = (value as UnityEngine.Vector2?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3 value_Vector3)
                return value_Vector3.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3?))
            {
                var convertedValue = (value as UnityEngine.Vector3?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4 value_Vector4)
                return value_Vector4.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4?))
            {
                var convertedValue = (value as UnityEngine.Vector4?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Quaternion value_Quaternion)
                return value_Quaternion.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Quaternion?))
            {
                var convertedValue = (value as UnityEngine.Quaternion?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Int value_Vector2Int)
                return value_Vector2Int.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Int?))
            {
                var convertedValue = (value as UnityEngine.Vector2Int?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Int value_Vector3Int)
                return value_Vector3Int.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Int?))
            {
                var convertedValue = (value as UnityEngine.Vector3Int?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Matrix4x4 value_Matrix4x4)
                return value_Matrix4x4.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Matrix4x4?))
            {
                var convertedValue = (value as UnityEngine.Matrix4x4?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Color value_Color)
                return value_Color.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Color?))
            {
                var convertedValue = (value as UnityEngine.Color?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Color32 value_Color32)
                return value_Color32.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Color32?))
            {
                var convertedValue = (value as UnityEngine.Color32?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Rect value_Rect)
                return value_Rect.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Rect?))
            {
                var convertedValue = (value as UnityEngine.Rect?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.RectInt value_RectInt)
                return value_RectInt.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.RectInt?))
            {
                var convertedValue = (value as UnityEngine.RectInt?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Bounds value_Bounds)
                return value_Bounds.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Bounds?))
            {
                var convertedValue = (value as UnityEngine.Bounds?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.QuaternionDouble value_QuaternionDouble)
                return value_QuaternionDouble.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.QuaternionDouble?))
            {
                var convertedValue = (value as UnityEngine.QuaternionDouble?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.ColorX value_ColorX)
                return value_ColorX.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.ColorX?))
            {
                var convertedValue = (value as UnityEngine.ColorX?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Bool value_Vector2Bool)
                return value_Vector2Bool.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Bool?))
            {
                var convertedValue = (value as UnityEngine.Vector2Bool?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Bool value_Vector3Bool)
                return value_Vector3Bool.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Bool?))
            {
                var convertedValue = (value as UnityEngine.Vector3Bool?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Bool value_Vector4Bool)
                return value_Vector4Bool.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Bool?))
            {
                var convertedValue = (value as UnityEngine.Vector4Bool?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Byte value_Vector2Byte)
                return value_Vector2Byte.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Byte?))
            {
                var convertedValue = (value as UnityEngine.Vector2Byte?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Byte value_Vector3Byte)
                return value_Vector3Byte.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Byte?))
            {
                var convertedValue = (value as UnityEngine.Vector3Byte?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Byte value_Vector4Byte)
                return value_Vector4Byte.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Byte?))
            {
                var convertedValue = (value as UnityEngine.Vector4Byte?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Ushort value_Vector2Ushort)
                return value_Vector2Ushort.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Ushort?))
            {
                var convertedValue = (value as UnityEngine.Vector2Ushort?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Ushort value_Vector3Ushort)
                return value_Vector3Ushort.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Ushort?))
            {
                var convertedValue = (value as UnityEngine.Vector3Ushort?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Ushort value_Vector4Ushort)
                return value_Vector4Ushort.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Ushort?))
            {
                var convertedValue = (value as UnityEngine.Vector4Ushort?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Uint value_Vector2Uint)
                return value_Vector2Uint.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Uint?))
            {
                var convertedValue = (value as UnityEngine.Vector2Uint?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Uint value_Vector3Uint)
                return value_Vector3Uint.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Uint?))
            {
                var convertedValue = (value as UnityEngine.Vector3Uint?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Uint value_Vector4Uint)
                return value_Vector4Uint.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Uint?))
            {
                var convertedValue = (value as UnityEngine.Vector4Uint?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Ulong value_Vector2Ulong)
                return value_Vector2Ulong.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Ulong?))
            {
                var convertedValue = (value as UnityEngine.Vector2Ulong?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Ulong value_Vector3Ulong)
                return value_Vector3Ulong.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Ulong?))
            {
                var convertedValue = (value as UnityEngine.Vector3Ulong?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Ulong value_Vector4Ulong)
                return value_Vector4Ulong.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Ulong?))
            {
                var convertedValue = (value as UnityEngine.Vector4Ulong?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Sbyte value_Vector2Sbyte)
                return value_Vector2Sbyte.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Sbyte?))
            {
                var convertedValue = (value as UnityEngine.Vector2Sbyte?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Sbyte value_Vector3Sbyte)
                return value_Vector3Sbyte.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Sbyte?))
            {
                var convertedValue = (value as UnityEngine.Vector3Sbyte?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Sbyte value_Vector4Sbyte)
                return value_Vector4Sbyte.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Sbyte?))
            {
                var convertedValue = (value as UnityEngine.Vector4Sbyte?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Short value_Vector2Short)
                return value_Vector2Short.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Short?))
            {
                var convertedValue = (value as UnityEngine.Vector2Short?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Short value_Vector3Short)
                return value_Vector3Short.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Short?))
            {
                var convertedValue = (value as UnityEngine.Vector3Short?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Short value_Vector4Short)
                return value_Vector4Short.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Short?))
            {
                var convertedValue = (value as UnityEngine.Vector4Short?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Long value_Vector2Long)
                return value_Vector2Long.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Long?))
            {
                var convertedValue = (value as UnityEngine.Vector2Long?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Long value_Vector3Long)
                return value_Vector3Long.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Long?))
            {
                var convertedValue = (value as UnityEngine.Vector3Long?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Long value_Vector4Long)
                return value_Vector4Long.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Long?))
            {
                var convertedValue = (value as UnityEngine.Vector4Long?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector2Double value_Vector2Double)
                return value_Vector2Double.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector2Double?))
            {
                var convertedValue = (value as UnityEngine.Vector2Double?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector3Double value_Vector3Double)
                return value_Vector3Double.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector3Double?))
            {
                var convertedValue = (value as UnityEngine.Vector3Double?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Vector4Double value_Vector4Double)
                return value_Vector4Double.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Vector4Double?))
            {
                var convertedValue = (value as UnityEngine.Vector4Double?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Matrix2x2 value_Matrix2x2)
                return value_Matrix2x2.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Matrix2x2?))
            {
                var convertedValue = (value as UnityEngine.Matrix2x2?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Matrix3x3 value_Matrix3x3)
                return value_Matrix3x3.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Matrix3x3?))
            {
                var convertedValue = (value as UnityEngine.Matrix3x3?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Matrix2x2Double value_Matrix2x2Double)
                return value_Matrix2x2Double.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Matrix2x2Double?))
            {
                var convertedValue = (value as UnityEngine.Matrix2x2Double?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Matrix3x3Double value_Matrix3x3Double)
                return value_Matrix3x3Double.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Matrix3x3Double?))
            {
                var convertedValue = (value as UnityEngine.Matrix3x3Double?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
                        if(value is UnityEngine.Matrix4x4Double value_Matrix4x4Double)
                return value_Matrix4x4Double.ToResoniteLink().ToResoniteLinkField();
            if(type == typeof(UnityEngine.Matrix4x4Double?))
            {
                var convertedValue = (value as UnityEngine.Matrix4x4Double?)?.ToResoniteLink();
                return convertedValue.ToResoniteLinkField();
            }
            
            // All other primitives
                    if(type == typeof(byte))
            {
                var field = new Field_byte();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(byte?))
                {
                    var field = new Field_Nullable_byte();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ushort))
            {
                var field = new Field_ushort();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ushort?))
                {
                    var field = new Field_Nullable_ushort();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(uint))
            {
                var field = new Field_uint();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(uint?))
                {
                    var field = new Field_Nullable_uint();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ulong))
            {
                var field = new Field_ulong();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ulong?))
                {
                    var field = new Field_Nullable_ulong();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(sbyte))
            {
                var field = new Field_sbyte();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(sbyte?))
                {
                    var field = new Field_Nullable_sbyte();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(short))
            {
                var field = new Field_short();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(short?))
                {
                    var field = new Field_Nullable_short();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(int))
            {
                var field = new Field_int();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(int?))
                {
                    var field = new Field_Nullable_int();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(long))
            {
                var field = new Field_long();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(long?))
                {
                    var field = new Field_Nullable_long();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float))
            {
                var field = new Field_float();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float?))
                {
                    var field = new Field_Nullable_float();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double))
            {
                var field = new Field_double();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double?))
                {
                    var field = new Field_Nullable_double();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(decimal))
            {
                var field = new Field_decimal();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(decimal?))
                {
                    var field = new Field_Nullable_decimal();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(bool))
            {
                var field = new Field_bool();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(bool?))
                {
                    var field = new Field_Nullable_bool();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(char))
            {
                var field = new Field_char();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(char?))
                {
                    var field = new Field_Nullable_char();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(string))
            {
                var field = new Field_string();
                field.BoxedValue = value;
                return field;
            }

            
                        if(type == typeof(Uri))
            {
                var field = new Field_Uri();
                field.BoxedValue = value;
                return field;
            }

            
                        if(type == typeof(DateTime))
            {
                var field = new Field_DateTime();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(DateTime?))
                {
                    var field = new Field_Nullable_DateTime();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(TimeSpan))
            {
                var field = new Field_TimeSpan();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(TimeSpan?))
                {
                    var field = new Field_Nullable_TimeSpan();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(color))
            {
                var field = new Field_color();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(color?))
                {
                    var field = new Field_Nullable_color();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(colorX))
            {
                var field = new Field_colorX();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(colorX?))
                {
                    var field = new Field_Nullable_colorX();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(color32))
            {
                var field = new Field_color32();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(color32?))
                {
                    var field = new Field_Nullable_color32();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(Rect))
            {
                var field = new Field_Rect();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(Rect?))
                {
                    var field = new Field_Nullable_Rect();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(IntRect))
            {
                var field = new Field_IntRect();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(IntRect?))
                {
                    var field = new Field_Nullable_IntRect();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(BoundingBox))
            {
                var field = new Field_BoundingBox();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(BoundingBox?))
                {
                    var field = new Field_Nullable_BoundingBox();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float2))
            {
                var field = new Field_float2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float2?))
                {
                    var field = new Field_Nullable_float2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double2))
            {
                var field = new Field_double2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double2?))
                {
                    var field = new Field_Nullable_double2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(byte2))
            {
                var field = new Field_byte2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(byte2?))
                {
                    var field = new Field_Nullable_byte2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ushort2))
            {
                var field = new Field_ushort2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ushort2?))
                {
                    var field = new Field_Nullable_ushort2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(uint2))
            {
                var field = new Field_uint2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(uint2?))
                {
                    var field = new Field_Nullable_uint2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ulong2))
            {
                var field = new Field_ulong2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ulong2?))
                {
                    var field = new Field_Nullable_ulong2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(sbyte2))
            {
                var field = new Field_sbyte2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(sbyte2?))
                {
                    var field = new Field_Nullable_sbyte2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(short2))
            {
                var field = new Field_short2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(short2?))
                {
                    var field = new Field_Nullable_short2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(int2))
            {
                var field = new Field_int2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(int2?))
                {
                    var field = new Field_Nullable_int2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(long2))
            {
                var field = new Field_long2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(long2?))
                {
                    var field = new Field_Nullable_long2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(bool2))
            {
                var field = new Field_bool2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(bool2?))
                {
                    var field = new Field_Nullable_bool2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float3))
            {
                var field = new Field_float3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float3?))
                {
                    var field = new Field_Nullable_float3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double3))
            {
                var field = new Field_double3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double3?))
                {
                    var field = new Field_Nullable_double3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(byte3))
            {
                var field = new Field_byte3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(byte3?))
                {
                    var field = new Field_Nullable_byte3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ushort3))
            {
                var field = new Field_ushort3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ushort3?))
                {
                    var field = new Field_Nullable_ushort3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(uint3))
            {
                var field = new Field_uint3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(uint3?))
                {
                    var field = new Field_Nullable_uint3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ulong3))
            {
                var field = new Field_ulong3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ulong3?))
                {
                    var field = new Field_Nullable_ulong3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(sbyte3))
            {
                var field = new Field_sbyte3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(sbyte3?))
                {
                    var field = new Field_Nullable_sbyte3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(short3))
            {
                var field = new Field_short3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(short3?))
                {
                    var field = new Field_Nullable_short3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(int3))
            {
                var field = new Field_int3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(int3?))
                {
                    var field = new Field_Nullable_int3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(long3))
            {
                var field = new Field_long3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(long3?))
                {
                    var field = new Field_Nullable_long3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(bool3))
            {
                var field = new Field_bool3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(bool3?))
                {
                    var field = new Field_Nullable_bool3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float4))
            {
                var field = new Field_float4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float4?))
                {
                    var field = new Field_Nullable_float4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double4))
            {
                var field = new Field_double4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double4?))
                {
                    var field = new Field_Nullable_double4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(byte4))
            {
                var field = new Field_byte4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(byte4?))
                {
                    var field = new Field_Nullable_byte4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ushort4))
            {
                var field = new Field_ushort4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ushort4?))
                {
                    var field = new Field_Nullable_ushort4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(uint4))
            {
                var field = new Field_uint4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(uint4?))
                {
                    var field = new Field_Nullable_uint4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(ulong4))
            {
                var field = new Field_ulong4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(ulong4?))
                {
                    var field = new Field_Nullable_ulong4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(sbyte4))
            {
                var field = new Field_sbyte4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(sbyte4?))
                {
                    var field = new Field_Nullable_sbyte4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(short4))
            {
                var field = new Field_short4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(short4?))
                {
                    var field = new Field_Nullable_short4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(int4))
            {
                var field = new Field_int4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(int4?))
                {
                    var field = new Field_Nullable_int4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(long4))
            {
                var field = new Field_long4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(long4?))
                {
                    var field = new Field_Nullable_long4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(bool4))
            {
                var field = new Field_bool4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(bool4?))
                {
                    var field = new Field_Nullable_bool4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(floatQ))
            {
                var field = new Field_floatQ();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(floatQ?))
                {
                    var field = new Field_Nullable_floatQ();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(doubleQ))
            {
                var field = new Field_doubleQ();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(doubleQ?))
                {
                    var field = new Field_Nullable_doubleQ();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float2x2))
            {
                var field = new Field_float2x2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float2x2?))
                {
                    var field = new Field_Nullable_float2x2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double2x2))
            {
                var field = new Field_double2x2();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double2x2?))
                {
                    var field = new Field_Nullable_double2x2();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float3x3))
            {
                var field = new Field_float3x3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float3x3?))
                {
                    var field = new Field_Nullable_float3x3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double3x3))
            {
                var field = new Field_double3x3();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double3x3?))
                {
                    var field = new Field_Nullable_double3x3();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(float4x4))
            {
                var field = new Field_float4x4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(float4x4?))
                {
                    var field = new Field_Nullable_float4x4();
                    field.BoxedValue = value;
                    return field;
                }
                
                        if(type == typeof(double4x4))
            {
                var field = new Field_double4x4();
                field.BoxedValue = value;
                return field;
            }

                            
                if(type == typeof(double4x4?))
                {
                    var field = new Field_Nullable_double4x4();
                    field.BoxedValue = value;
                    return field;
                }
                
            
        throw new NotSupportedException($"Unsupported value type: {typeof(T).FullName}");
    }

    public static SyncArray ToResoniteLinkArray<T>(this IEnumerable<T> values)
    {
        var type = typeof(T);

        // Unity Primitives (and our extensions)
                    if(values is IEnumerable<UnityEngine.Vector2> values_Vector2)
                return values_Vector2.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3> values_Vector3)
                return values_Vector3.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4> values_Vector4)
                return values_Vector4.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Quaternion> values_Quaternion)
                return values_Quaternion.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Int> values_Vector2Int)
                return values_Vector2Int.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Int> values_Vector3Int)
                return values_Vector3Int.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Matrix4x4> values_Matrix4x4)
                return values_Matrix4x4.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Color> values_Color)
                return values_Color.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Color32> values_Color32)
                return values_Color32.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Rect> values_Rect)
                return values_Rect.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.RectInt> values_RectInt)
                return values_RectInt.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Bounds> values_Bounds)
                return values_Bounds.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.QuaternionDouble> values_QuaternionDouble)
                return values_QuaternionDouble.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.ColorX> values_ColorX)
                return values_ColorX.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Bool> values_Vector2Bool)
                return values_Vector2Bool.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Bool> values_Vector3Bool)
                return values_Vector3Bool.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Bool> values_Vector4Bool)
                return values_Vector4Bool.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Byte> values_Vector2Byte)
                return values_Vector2Byte.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Byte> values_Vector3Byte)
                return values_Vector3Byte.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Byte> values_Vector4Byte)
                return values_Vector4Byte.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Ushort> values_Vector2Ushort)
                return values_Vector2Ushort.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Ushort> values_Vector3Ushort)
                return values_Vector3Ushort.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Ushort> values_Vector4Ushort)
                return values_Vector4Ushort.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Uint> values_Vector2Uint)
                return values_Vector2Uint.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Uint> values_Vector3Uint)
                return values_Vector3Uint.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Uint> values_Vector4Uint)
                return values_Vector4Uint.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Ulong> values_Vector2Ulong)
                return values_Vector2Ulong.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Ulong> values_Vector3Ulong)
                return values_Vector3Ulong.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Ulong> values_Vector4Ulong)
                return values_Vector4Ulong.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Sbyte> values_Vector2Sbyte)
                return values_Vector2Sbyte.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Sbyte> values_Vector3Sbyte)
                return values_Vector3Sbyte.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Sbyte> values_Vector4Sbyte)
                return values_Vector4Sbyte.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Short> values_Vector2Short)
                return values_Vector2Short.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Short> values_Vector3Short)
                return values_Vector3Short.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Short> values_Vector4Short)
                return values_Vector4Short.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Long> values_Vector2Long)
                return values_Vector2Long.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Long> values_Vector3Long)
                return values_Vector3Long.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Long> values_Vector4Long)
                return values_Vector4Long.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector2Double> values_Vector2Double)
                return values_Vector2Double.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector3Double> values_Vector3Double)
                return values_Vector3Double.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Vector4Double> values_Vector4Double)
                return values_Vector4Double.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Matrix2x2> values_Matrix2x2)
                return values_Matrix2x2.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Matrix3x3> values_Matrix3x3)
                return values_Matrix3x3.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Matrix2x2Double> values_Matrix2x2Double)
                return values_Matrix2x2Double.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Matrix3x3Double> values_Matrix3x3Double)
                return values_Matrix3x3Double.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
                        if(values is IEnumerable<UnityEngine.Matrix4x4Double> values_Matrix4x4Double)
                return values_Matrix4x4Double.Select(v => v.ToResoniteLink()).ToResoniteLinkArray();
            
        // All other primitives
                    if(type == typeof(byte))
            {
                var array = new Array_byte();
                array.Values = values.Cast<byte>().ToList();
                return array;
            }
                        if(type == typeof(ushort))
            {
                var array = new Array_ushort();
                array.Values = values.Cast<ushort>().ToList();
                return array;
            }
                        if(type == typeof(uint))
            {
                var array = new Array_uint();
                array.Values = values.Cast<uint>().ToList();
                return array;
            }
                        if(type == typeof(ulong))
            {
                var array = new Array_ulong();
                array.Values = values.Cast<ulong>().ToList();
                return array;
            }
                        if(type == typeof(sbyte))
            {
                var array = new Array_sbyte();
                array.Values = values.Cast<sbyte>().ToList();
                return array;
            }
                        if(type == typeof(short))
            {
                var array = new Array_short();
                array.Values = values.Cast<short>().ToList();
                return array;
            }
                        if(type == typeof(int))
            {
                var array = new Array_int();
                array.Values = values.Cast<int>().ToList();
                return array;
            }
                        if(type == typeof(long))
            {
                var array = new Array_long();
                array.Values = values.Cast<long>().ToList();
                return array;
            }
                        if(type == typeof(float))
            {
                var array = new Array_float();
                array.Values = values.Cast<float>().ToList();
                return array;
            }
                        if(type == typeof(double))
            {
                var array = new Array_double();
                array.Values = values.Cast<double>().ToList();
                return array;
            }
                        if(type == typeof(decimal))
            {
                var array = new Array_decimal();
                array.Values = values.Cast<decimal>().ToList();
                return array;
            }
                        if(type == typeof(bool))
            {
                var array = new Array_bool();
                array.Values = values.Cast<bool>().ToList();
                return array;
            }
                        if(type == typeof(char))
            {
                var array = new Array_char();
                array.Values = values.Cast<char>().ToList();
                return array;
            }
                        if(type == typeof(string))
            {
                var array = new Array_string();
                array.Values = values.Cast<string>().ToList();
                return array;
            }
                        if(type == typeof(Uri))
            {
                var array = new Array_Uri();
                array.Values = values.Cast<Uri>().ToList();
                return array;
            }
                        if(type == typeof(DateTime))
            {
                var array = new Array_DateTime();
                array.Values = values.Cast<DateTime>().ToList();
                return array;
            }
                        if(type == typeof(TimeSpan))
            {
                var array = new Array_TimeSpan();
                array.Values = values.Cast<TimeSpan>().ToList();
                return array;
            }
                        if(type == typeof(color))
            {
                var array = new Array_color();
                array.Values = values.Cast<color>().ToList();
                return array;
            }
                        if(type == typeof(colorX))
            {
                var array = new Array_colorX();
                array.Values = values.Cast<colorX>().ToList();
                return array;
            }
                        if(type == typeof(color32))
            {
                var array = new Array_color32();
                array.Values = values.Cast<color32>().ToList();
                return array;
            }
                        if(type == typeof(Rect))
            {
                var array = new Array_Rect();
                array.Values = values.Cast<Rect>().ToList();
                return array;
            }
                        if(type == typeof(IntRect))
            {
                var array = new Array_IntRect();
                array.Values = values.Cast<IntRect>().ToList();
                return array;
            }
                        if(type == typeof(BoundingBox))
            {
                var array = new Array_BoundingBox();
                array.Values = values.Cast<BoundingBox>().ToList();
                return array;
            }
                        if(type == typeof(float2))
            {
                var array = new Array_float2();
                array.Values = values.Cast<float2>().ToList();
                return array;
            }
                        if(type == typeof(double2))
            {
                var array = new Array_double2();
                array.Values = values.Cast<double2>().ToList();
                return array;
            }
                        if(type == typeof(byte2))
            {
                var array = new Array_byte2();
                array.Values = values.Cast<byte2>().ToList();
                return array;
            }
                        if(type == typeof(ushort2))
            {
                var array = new Array_ushort2();
                array.Values = values.Cast<ushort2>().ToList();
                return array;
            }
                        if(type == typeof(uint2))
            {
                var array = new Array_uint2();
                array.Values = values.Cast<uint2>().ToList();
                return array;
            }
                        if(type == typeof(ulong2))
            {
                var array = new Array_ulong2();
                array.Values = values.Cast<ulong2>().ToList();
                return array;
            }
                        if(type == typeof(sbyte2))
            {
                var array = new Array_sbyte2();
                array.Values = values.Cast<sbyte2>().ToList();
                return array;
            }
                        if(type == typeof(short2))
            {
                var array = new Array_short2();
                array.Values = values.Cast<short2>().ToList();
                return array;
            }
                        if(type == typeof(int2))
            {
                var array = new Array_int2();
                array.Values = values.Cast<int2>().ToList();
                return array;
            }
                        if(type == typeof(long2))
            {
                var array = new Array_long2();
                array.Values = values.Cast<long2>().ToList();
                return array;
            }
                        if(type == typeof(bool2))
            {
                var array = new Array_bool2();
                array.Values = values.Cast<bool2>().ToList();
                return array;
            }
                        if(type == typeof(float3))
            {
                var array = new Array_float3();
                array.Values = values.Cast<float3>().ToList();
                return array;
            }
                        if(type == typeof(double3))
            {
                var array = new Array_double3();
                array.Values = values.Cast<double3>().ToList();
                return array;
            }
                        if(type == typeof(byte3))
            {
                var array = new Array_byte3();
                array.Values = values.Cast<byte3>().ToList();
                return array;
            }
                        if(type == typeof(ushort3))
            {
                var array = new Array_ushort3();
                array.Values = values.Cast<ushort3>().ToList();
                return array;
            }
                        if(type == typeof(uint3))
            {
                var array = new Array_uint3();
                array.Values = values.Cast<uint3>().ToList();
                return array;
            }
                        if(type == typeof(ulong3))
            {
                var array = new Array_ulong3();
                array.Values = values.Cast<ulong3>().ToList();
                return array;
            }
                        if(type == typeof(sbyte3))
            {
                var array = new Array_sbyte3();
                array.Values = values.Cast<sbyte3>().ToList();
                return array;
            }
                        if(type == typeof(short3))
            {
                var array = new Array_short3();
                array.Values = values.Cast<short3>().ToList();
                return array;
            }
                        if(type == typeof(int3))
            {
                var array = new Array_int3();
                array.Values = values.Cast<int3>().ToList();
                return array;
            }
                        if(type == typeof(long3))
            {
                var array = new Array_long3();
                array.Values = values.Cast<long3>().ToList();
                return array;
            }
                        if(type == typeof(bool3))
            {
                var array = new Array_bool3();
                array.Values = values.Cast<bool3>().ToList();
                return array;
            }
                        if(type == typeof(float4))
            {
                var array = new Array_float4();
                array.Values = values.Cast<float4>().ToList();
                return array;
            }
                        if(type == typeof(double4))
            {
                var array = new Array_double4();
                array.Values = values.Cast<double4>().ToList();
                return array;
            }
                        if(type == typeof(byte4))
            {
                var array = new Array_byte4();
                array.Values = values.Cast<byte4>().ToList();
                return array;
            }
                        if(type == typeof(ushort4))
            {
                var array = new Array_ushort4();
                array.Values = values.Cast<ushort4>().ToList();
                return array;
            }
                        if(type == typeof(uint4))
            {
                var array = new Array_uint4();
                array.Values = values.Cast<uint4>().ToList();
                return array;
            }
                        if(type == typeof(ulong4))
            {
                var array = new Array_ulong4();
                array.Values = values.Cast<ulong4>().ToList();
                return array;
            }
                        if(type == typeof(sbyte4))
            {
                var array = new Array_sbyte4();
                array.Values = values.Cast<sbyte4>().ToList();
                return array;
            }
                        if(type == typeof(short4))
            {
                var array = new Array_short4();
                array.Values = values.Cast<short4>().ToList();
                return array;
            }
                        if(type == typeof(int4))
            {
                var array = new Array_int4();
                array.Values = values.Cast<int4>().ToList();
                return array;
            }
                        if(type == typeof(long4))
            {
                var array = new Array_long4();
                array.Values = values.Cast<long4>().ToList();
                return array;
            }
                        if(type == typeof(bool4))
            {
                var array = new Array_bool4();
                array.Values = values.Cast<bool4>().ToList();
                return array;
            }
                        if(type == typeof(floatQ))
            {
                var array = new Array_floatQ();
                array.Values = values.Cast<floatQ>().ToList();
                return array;
            }
                        if(type == typeof(doubleQ))
            {
                var array = new Array_doubleQ();
                array.Values = values.Cast<doubleQ>().ToList();
                return array;
            }
                        if(type == typeof(float2x2))
            {
                var array = new Array_float2x2();
                array.Values = values.Cast<float2x2>().ToList();
                return array;
            }
                        if(type == typeof(double2x2))
            {
                var array = new Array_double2x2();
                array.Values = values.Cast<double2x2>().ToList();
                return array;
            }
                        if(type == typeof(float3x3))
            {
                var array = new Array_float3x3();
                array.Values = values.Cast<float3x3>().ToList();
                return array;
            }
                        if(type == typeof(double3x3))
            {
                var array = new Array_double3x3();
                array.Values = values.Cast<double3x3>().ToList();
                return array;
            }
                        if(type == typeof(float4x4))
            {
                var array = new Array_float4x4();
                array.Values = values.Cast<float4x4>().ToList();
                return array;
            }
                        if(type == typeof(double4x4))
            {
                var array = new Array_double4x4();
                array.Values = values.Cast<double4x4>().ToList();
                return array;
            }
            
        throw new NotSupportedException($"Unsupported value type: {typeof(T).FullName}");
    }
}