name: 'Build UnityPackage.'

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  unitypackage:
    runs-on: ubuntu-latest

    name: 'Build UnityPackage.'

    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'

      - name: 'Pull Unity from cache'
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: unity-setup-linux-2019.4.19f1-windows-mono
          path: /home/runner/Unity/Hub/Editor

      - name: 'Install Unity'
        continue-on-error: true
        run: |
          curl -sL https://hub.unity3d.com/linux/keys/public | sudo gpg --dearmor -o /usr/share/keyrings/Unity_Technologies_ApS.gpg
          sudo tee /etc/apt/sources.list.d/unity-cli.sources <<'EOF'
          Types: deb
          URIs: https://hub.unity3d.com/linux/repos/deb
          Suites: unstable
          Components: main
          Signed-By: /usr/share/keyrings/Unity_Technologies_ApS.gpg
          EOF

          sudo apt-get update && sudo apt-get install -y unity-cli

          unity editors -i
          unity install 6000.3.10f1 -a x86_64 -m windows-mono --cm

      - name: 'Activate Unity editor'
        env:
          UNITY_NO_CLI_INVOKED_TELEMETRY: false
        run: |
          unity auth login --client-id ${{ secrets.UNITY_SERVICE_ACCOUNT_ID }} --client-secret ${{ secrets.UNITY_SERVICE_ACCOUNT_SECRET }}

          /home/runner/Unity/Hub/Editor/6000.3.10f1/Editor/Unity -quit -batchmode -nographics -serial ${{ secrets.UNITY_CI_LICENSE_ID }} -username ${{ secrets.UNITY_CI_USERNAME }} -password ${{ secrets.UNITY_CI_PASSWORD }}

      - name: 'Build Package'
        run: /home/runner/Unity/Hub/Editor/6000.3.10f1/Editor/Unity -quit -batchmode -nographics -projectPath $(pwd) -executeMethod ResoniteSDK_Builder.BuildUnityPackage
  
      - name: 'Upload packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # V7.0.1
        with:
          name: 'Resonite.UnitySDK'
          path: Builds/*.unitypackage

      - name: 'Publish package to release if any.'
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: 'Builds/ResoniteSDK.unitypackage'
